# Copyright (c) 2019 Kekeho (Hiroki Takemura)
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

FROM python:3.7.3-slim-stretch

COPY ./entrypoint.sh /
ENTRYPOINT [ "sh", "entrypoint.sh" ]
